on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install Host Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.7.2
        host: 'mac'
        target: 'desktop'
        dir: './'
        arch: 'clang_64'
        tools: 'tools_qtcreator'

    - name: Package
      run: |
        ls

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./
