on:
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
    - name: Install Host Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.7.2
        host: 'linux'
        target: 'desktop'
        path: './'
        arch: 'linux_gcc_64'
        tools: 'tools_ninja tools_cmake'

    - name: Package
      run: |
        ls

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./
